# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - bdsagroup19chirpremotedb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build src/Chirp.CSVDBService/Chirp.CSVDBService.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish src/Chirp.CSVDBService/Chirp.CSVDBService.csproj -c Release -o ./publish_output

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: webapp-artifact
          path: ./publish_output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp-artifact
          path: ./deploy_package

      - name: Zip artifact for deployment
        run: |
          cd deploy_package/webapp-artifact
          zip -r ../../app.zip .
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E0D16A5DDDC043B2AE9631ABFCE8624A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9D48B95B0A764ECEB8131FEAE831494B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BFFAB5CF95C94E7D90519A47A37CC695 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bdsagroup19chirpremotedb'
          slot-name: 'Production'
          package: app.zip
          